package Html.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptHeaderTag = createDescriptorForHeaderTag();
  /*package*/ final ConceptDescriptor myConceptHrefTag = createDescriptorForHrefTag();
  /*package*/ final ConceptDescriptor myConceptHtmlDocument = createDescriptorForHtmlDocument();
  /*package*/ final ConceptDescriptor myConceptHtmlElement = createDescriptorForHtmlElement();
  /*package*/ final ConceptDescriptor myConceptListItemTag = createDescriptorForListItemTag();
  /*package*/ final ConceptDescriptor myConceptParagraphTag = createDescriptorForParagraphTag();
  /*package*/ final ConceptDescriptor myConceptTableBody = createDescriptorForTableBody();
  /*package*/ final ConceptDescriptor myConceptTableColumns = createDescriptorForTableColumns();
  /*package*/ final ConceptDescriptor myConceptTableHead = createDescriptorForTableHead();
  /*package*/ final ConceptDescriptor myConceptTableRow = createDescriptorForTableRow();
  /*package*/ final ConceptDescriptor myConceptTableTag = createDescriptorForTableTag();
  /*package*/ final ConceptDescriptor myConceptTextElement = createDescriptorForTextElement();
  /*package*/ final ConceptDescriptor myConceptUnorderedListTag = createDescriptorForUnorderedListTag();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptHeaderTag, myConceptHrefTag, myConceptHtmlDocument, myConceptHtmlElement, myConceptListItemTag, myConceptParagraphTag, myConceptTableBody, myConceptTableColumns, myConceptTableHead, myConceptTableRow, myConceptTableTag, myConceptTextElement, myConceptUnorderedListTag);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.HeaderTag:
        return myConceptHeaderTag;
      case LanguageConceptSwitch.HrefTag:
        return myConceptHrefTag;
      case LanguageConceptSwitch.HtmlDocument:
        return myConceptHtmlDocument;
      case LanguageConceptSwitch.HtmlElement:
        return myConceptHtmlElement;
      case LanguageConceptSwitch.ListItemTag:
        return myConceptListItemTag;
      case LanguageConceptSwitch.ParagraphTag:
        return myConceptParagraphTag;
      case LanguageConceptSwitch.TableBody:
        return myConceptTableBody;
      case LanguageConceptSwitch.TableColumns:
        return myConceptTableColumns;
      case LanguageConceptSwitch.TableHead:
        return myConceptTableHead;
      case LanguageConceptSwitch.TableRow:
        return myConceptTableRow;
      case LanguageConceptSwitch.TableTag:
        return myConceptTableTag;
      case LanguageConceptSwitch.TextElement:
        return myConceptTextElement;
      case LanguageConceptSwitch.UnorderedListTag:
        return myConceptUnorderedListTag;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForHeaderTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "HeaderTag", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc20057L);
    b.class_(false, false, false);
    // extends: Html.structure.HtmlElement
    b.super_(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbcf4e6L);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512834135");
    b.version(3);
    b.property("content", 0x214ad0a17bc201deL).type(PrimitiveTypeId.STRING).origin("2398959143512834526").done();
    b.alias("Header");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHrefTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "HrefTag", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x46aed3cb2881e616L);
    b.class_(false, false, false);
    // extends: Html.structure.HtmlElement
    b.super_(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbcf4e6L);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/5093241098114033174");
    b.version(3);
    b.property("link", 0x46aed3cb2881e9d9L).type(PrimitiveTypeId.STRING).origin("5093241098114034137").done();
    b.property("content", 0x46aed3cb2881eb95L).type(PrimitiveTypeId.STRING).origin("5093241098114034581").done();
    b.alias("Reference");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHtmlDocument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "HtmlDocument", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbce2a5L);
    b.class_(false, false, true);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512498853");
    b.version(3);
    b.property("title", 0x214ad0a17bbead05L).type(PrimitiveTypeId.STRING).origin("2398959143512616197").done();
    b.aggregate("tags", 0x214ad0a17bbdd5dcL).target(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbcf4e6L).optional(true).ordered(true).multiple(true).origin("2398959143512561116").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHtmlElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "HtmlElement", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbcf4e6L);
    b.class_(false, true, false);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512503526");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForListItemTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "ListItemTag", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2254aL);
    b.class_(false, false, false);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512843594");
    b.version(3);
    b.property("content", 0x214ad0a17bc27013L).type(PrimitiveTypeId.STRING).origin("2398959143512862739").done();
    b.alias("Item");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParagraphTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "ParagraphTag", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc17153L);
    b.class_(false, false, false);
    // extends: Html.structure.HtmlElement
    b.super_(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbcf4e6L);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512797523");
    b.version(3);
    b.property("content", 0x214ad0a17bc18c67L).type(PrimitiveTypeId.STRING).origin("2398959143512804455").done();
    b.alias("Paragraph");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTableBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "TableBody", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2bc98L);
    b.class_(false, false, false);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512882328");
    b.version(3);
    b.aggregate("rows", 0x214ad0a17bc2ce03L).target(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2cf8cL).optional(true).ordered(true).multiple(true).origin("2398959143512886787").done();
    b.alias("Body");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTableColumns() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "TableColumns", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2dc43L);
    b.class_(false, false, false);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512890435");
    b.version(3);
    b.property("content", 0x214ad0a17bc2df36L).type(PrimitiveTypeId.STRING).origin("2398959143512891190").done();
    b.alias("Columns");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTableHead() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "TableHead", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2a839L);
    b.class_(false, false, false);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512877113");
    b.version(3);
    b.property("content", 0x214ad0a17bc3596eL).type(PrimitiveTypeId.STRING).origin("2398959143512922478").done();
    b.alias("Head");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTableRow() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "TableRow", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2cf8cL);
    b.class_(false, false, false);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512887180");
    b.version(3);
    b.aggregate("columns", 0x214ad0a17bc2d5a7L).target(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2dc43L).optional(true).ordered(true).multiple(true).origin("2398959143512888743").done();
    b.alias("Row");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTableTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "TableTag", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc29f5fL);
    b.class_(false, false, false);
    // extends: Html.structure.HtmlElement
    b.super_(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbcf4e6L);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512874847");
    b.version(3);
    b.aggregate("head", 0x214ad0a17bc2c15fL).target(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2a839L).optional(true).ordered(true).multiple(false).origin("2398959143512883551").done();
    b.aggregate("body", 0x214ad0a17bc2c763L).target(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2bc98L).optional(true).ordered(true).multiple(false).origin("2398959143512885091").done();
    b.alias("Table");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTextElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "TextElement", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x46aed3cb288420baL);
    b.class_(false, false, false);
    // extends: Html.structure.HtmlElement
    b.super_(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbcf4e6L);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/5093241098114179258");
    b.version(3);
    b.property("content", 0x46aed3cb288429dfL).type(PrimitiveTypeId.STRING).origin("5093241098114181599").done();
    b.alias("Text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUnorderedListTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Html", "UnorderedListTag", 0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc22aafL);
    b.class_(false, false, false);
    // extends: Html.structure.HtmlElement
    b.super_(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbcf4e6L);
    b.origin("r:399afdf6-b352-4a0f-804f-7d424455e497(Html.structure)/2398959143512844975");
    b.version(3);
    b.aggregate("items", 0x214ad0a17bc23718L).target(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2254aL).optional(true).ordered(true).multiple(true).origin("2398959143512848152").done();
    b.alias("Unordered List");
    return b.create();
  }
}
