package Html.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class HeaderTag_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<h1>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.content$oCVr));
    tgs.append("</h1>\n");
  }

  private static final class PROPS {
    /*package*/ static final SProperty content$oCVr = MetaAdapterFactory.getProperty(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc20057L, 0x214ad0a17bc201deL, "content");
  }
}
