package Html.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class HrefTag_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<a href=\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.link$OzJr));
    tgs.append("\">");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.content$3c$O));
    tgs.append("</a>");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty link$OzJr = MetaAdapterFactory.getProperty(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x46aed3cb2881e616L, 0x46aed3cb2881e9d9L, "link");
    /*package*/ static final SProperty content$3c$O = MetaAdapterFactory.getProperty(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x46aed3cb2881e616L, 0x46aed3cb2881eb95L, "content");
  }
}
