package Html.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class HtmlDocument_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<html>");
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("<head>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<title>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.title$TZV6));
    tgs.append("</title>");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("</head>");
    tgs.newLine();
    tgs.indent();
    tgs.append("<body>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.tags$Yxxo)) {
      tgs.appendNode(item);
    }
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("</body>");
    tgs.newLine();
    tgs.decreaseIndent();
    tgs.indent();
    tgs.append("</html>\n");

  }

  private static final class PROPS {
    /*package*/ static final SProperty title$TZV6 = MetaAdapterFactory.getProperty(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbce2a5L, 0x214ad0a17bbead05L, "title");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink tags$Yxxo = MetaAdapterFactory.getContainmentLink(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bbce2a5L, 0x214ad0a17bbdd5dcL, "tags");
  }
}
