package Html.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TableHead_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<thead>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<th>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.content$Tqpm));
    tgs.append("</th>");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("</thead>");
    tgs.newLine();

  }

  private static final class PROPS {
    /*package*/ static final SProperty content$Tqpm = MetaAdapterFactory.getProperty(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc2a839L, 0x214ad0a17bc3596eL, "content");
  }
}
