package Html.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TableTag_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<table>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.head$1bRH));
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.body$asGy));
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("</table>");
    tgs.newLine();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink head$1bRH = MetaAdapterFactory.getContainmentLink(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc29f5fL, 0x214ad0a17bc2c15fL, "head");
    /*package*/ static final SContainmentLink body$asGy = MetaAdapterFactory.getContainmentLink(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x214ad0a17bc29f5fL, 0x214ad0a17bc2c763L, "body");
  }
}
