package Html.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextElement_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.content$nrVY));
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty content$nrVY = MetaAdapterFactory.getProperty(0x9047bdebbe544bdaL, 0xac2865e4c26965daL, 0x46aed3cb288420baL, 0x46aed3cb288429dfL, "content");
  }
}
